env:
  global:
    - CODECOV_TOKEN=603131ba-a477-4093-a9f5-baadc16b37cb

language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw


after_success:
  - bash <(curl -s https://codecov.io/bash)