spring:
    datasource:
        password: password
        url: jdbc:mysql://localhost:3306/db
        username: user_test
    flyway:
        password: password
        schemas: db
        url: jdbc:mysql://localhost:3306/db
        user: user_test
        baseline-on-migrate: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
